force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <description>Sell/Buy orders</description>
    <label>Exchange Order</label>
    <nameField>
        <displayFormat>ORDER-{00000}</displayFormat>
        <label>Exchange Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of the sell/buy order</description>
    <inlineHelpText>status of the sell/buy order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/Exchange_Order_Match__c.object-meta.xml
<CustomObject>
    <description>representing the execution of a trade between sell and buy orders.</description>
    <label>Exchange Order Match</label>
    <nameField>
        <displayFormat>OrderMatch-{00000}</displayFormat>
        <label>Exchange Order Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Order Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestExchangeOrderProcessing.cls
@isTest
private class TestExchangeOrderProcessing {
/** 
    verifies order creation and their statuses
*/
 static testMethod void testOrderCreation() {
    Exchange_Order__c sellOrder = TestUtility.createOrder('Sell', 'Market', 100, 10,'');
    Exchange_Order__c buyOrder = TestUtility.createOrder('Buy', 'Market', 101, 10,'');
    Test.startTest();
    sellOrder = TestUtility.getOrderById(sellOrder.id);
    buyOrder = TestUtility.getOrderById(buyOrder.id);
    System.assertEquals(sellOrder.Status__c, 'Open');
    System.assertEquals(buyOrder.Status__c, 'Open');
    Test.stopTest();
 }
 
/** 
    verifies order filling on creation/finding of match and verifies their statuses as Filled
*/
 static testMethod void testOrderMatch() {
    Exchange_Order__c sellOrder = TestUtility.createOrder('Sell', 'Market', 100, 10,'');
    Exchange_Order__c buyOrder = TestUtility.createOrder('Buy', 'Market', 100, 10,'');
    Exchange_Order_Match__c orderMatch = TestUtility.createOrderMatch(sellOrder.id, buyOrder.id);
    Test.startTest();
    sellOrder = TestUtility.getOrderById(sellOrder.id);
    buyOrder = TestUtility.getOrderById(buyOrder.id);
    System.assertEquals(sellOrder.Status__c, 'Filled');
    System.assertEquals(buyOrder.Status__c, 'Filled');
    Test.stopTest();
 }
 
 /**
     verifies whether limit order with no match has been cancelled at the end with status as Cancelled
 */
 static testMethod void testLimitOrderCancelling() {
    Exchange_Order__c sellOrder = TestUtility.createOrder('Sell', 'Limit', 100, 10,'FoK (Fill or Kill)');
    Test.startTest();
    sellOrder = TestUtility.getOrderById(sellOrder.id);
    System.assertEquals(sellOrder.Status__c, 'Cancelled');
    Test.stopTest();
 }
}