force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <description>Sell/Buy orders</description>
    <label>Exchange Order</label>
    <nameField>
        <displayFormat>ORDER-{00000}</displayFormat>
        <label>Exchange Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <description>Represents either a bid (buy) or an ask (sell) order</description>
    <inlineHelpText>Represents either a bid (buy) or an ask (sell) order</inlineHelpText>
    <label>Order Side</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>the total amount paid/received for filled orders and for non-filled orders this will be 0.</description>
    <formula>IF(ISPICKVAL(Status__c, &quot;Filled&quot;) ,  Quantity__c *  Price__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>the total amount paid/received for filled orders and for non-filled orders this will be 0.</inlineHelpText>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Represents either a market or limit order</description>
    <inlineHelpText>Represents either a market or limit order</inlineHelpText>
    <label>Order Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of securities ordered (sell/buy)</description>
    <inlineHelpText>Represents the number of securities ordered (sell/buy)</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>holds ordered security</description>
    <inlineHelpText>holds ordered security</inlineHelpText>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Time_in_Force__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Force__c</fullName>
    <description>Specifies the type and time till the limit order is valid.</description>
    <inlineHelpText>Specifies the type and time till the limit order is valid.</inlineHelpText>
    <label>Time in Force</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>GTC (Good Till Cancel)</fullName>
            </value>
            <value>
                <fullName>FoK (Fill or Kill)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>It represent a security on the exchange</description>
    <label>Security</label>
    <nameField>
        <label>Securies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ExchangeOrderRestResource.cls
/**
 * ExchangeOrderRestResource Description
 * It's Rest resource exposed with apis to handle create, update exchange orders and also for fetching order information.
 * @author undefined
 * @version Version number
 */
@RestResource(urlMapping='/order/*')
global class ExchangeOrderRestResource {

    /**
     * createOrder Description
     * creates exchange order with the given information.
     * @param orderToCreate (Exchange_Order__c): input order object to create.
     * @return String: returns status with created order information.
     */
    @HttpPost
    global static String createOrder(Exchange_Order__c orderToCreate){
       String result = '';
       try{
           insert orderToCreate;
           result = 'Order with id: '+orderToCreate.id+'has been created successfully as : '+orderToCreate;
       }catch(DmlException ex){
           result = 'Order creation has been failed with error :'+ex.getMessage();
       }
       return result;
    }
    
    /**
     * updateOrder Description
     * updates the exchange order as given information.
     * @param orderToUpdate (Exchange_Order__c): input order object
     * @return String: returns status with updated order information.
     */
    @HttpPut
    global static String updateOrder(Exchange_Order__c orderToUpdate){
       String result = '';
       try{
           update orderToUpdate;
           result = 'Order with id: '+orderToUpdate.id+'has been updated successfully as: '+orderToUpdate;
       }catch(DmlException ex){
           result = 'Order update has been failed with error :'+ex.getMessage();
       }
       return result;
    }
    
    /**
     * getOrder Description
     * queries and returns the information for the given order id.
     * @return String: returns order information.
     */
    @HttpGet
    global static String getOrder(){
        String orderId = RestContext.request.params.get('id');
        try{ 
            List<Exchange_Order__c> orderRecord = [SELECT Id, Name, Security__c, Order_Side__c,Order_Type__c, Quantity__c,Time_In_Force__c,Order_Total__c FROM Exchange_Order__c WHERE Id = :orderId WITH SECURITY_ENFORCED LIMIT 1];
            if(orderRecord.isEmpty()){
                return 'no records found for the given id: '+orderId; 
            }else{
                return 'fetched order for the given id: '+orderRecord; 
            }
        }catch(QueryException ex){
            return  'Order Fetch has been failed with error :'+ex.getMessage();
        }
    }
}