force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <description>Sell/Buy orders</description>
    <label>Exchange Order</label>
    <nameField>
        <displayFormat>ORDER-{00000}</displayFormat>
        <label>Exchange Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <description>Represents either a bid (buy) or an ask (sell) order</description>
    <inlineHelpText>Represents either a bid (buy) or an ask (sell) order</inlineHelpText>
    <label>Order Side</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <description>the total amount paid/received for filled orders and for non-filled orders this will be 0.</description>
    <formula>IF(ISPICKVAL(Status__c, &quot;Filled&quot;) ,  Quantity__c *  Price__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>the total amount paid/received for filled orders and for non-filled orders this will be 0.</inlineHelpText>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Represents either a market or limit order</description>
    <inlineHelpText>Represents either a market or limit order</inlineHelpText>
    <label>Order Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Bid or ask price, only relevant for limit orders.</description>
    <inlineHelpText>Bid or ask price, only relevant for limit orders.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of securities ordered (sell/buy)</description>
    <inlineHelpText>Represents the number of securities ordered (sell/buy)</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>holds ordered security</description>
    <inlineHelpText>holds ordered security</inlineHelpText>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of the sell/buy order</description>
    <inlineHelpText>status of the sell/buy order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Time_in_Force__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Force__c</fullName>
    <description>Specifies the type and time till the limit order is valid.</description>
    <inlineHelpText>Specifies the type and time till the limit order is valid.</inlineHelpText>
    <label>Time in Force</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>GTC (Good Till Cancel)</fullName>
            </value>
            <value>
                <fullName>FoK (Fill or Kill)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/Exchange_Order_Match__c.object-meta.xml
<CustomObject>
    <description>representing the execution of a trade between sell and buy orders.</description>
    <label>Exchange Order Match</label>
    <nameField>
        <displayFormat>OrderMatch-{00000}</displayFormat>
        <label>Exchange Order Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Order Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Buy_Order__c.field-meta.xml
<CustomField>
    <fullName>Buy_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to exchange order(buy)</description>
    <inlineHelpText>lookup to exchange order(buy)</inlineHelpText>
    <label>Buy Order</label>
    <referenceTo>Exchange_Order__c</referenceTo>
    <relationshipLabel>Exchange Order Matches</relationshipLabel>
    <relationshipName>Exchange_Order_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price matched at.</description>
    <inlineHelpText>Price matched at.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Matched quantity</description>
    <inlineHelpText>Matched quantity</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Sell_Order__c.field-meta.xml
<CustomField>
    <fullName>Sell_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to exchange order(sell)</description>
    <inlineHelpText>lookup to exchange order(sell)</inlineHelpText>
    <label>Sell Order</label>
    <referenceTo>Exchange_Order__c</referenceTo>
    <relationshipLabel>Exchange Order Matches (Sell Order)</relationshipLabel>
    <relationshipName>Exchange_Order_Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FilledExchangeOrders__e/FilledExchangeOrders__e.object-meta.xml
<CustomObject>
    <description>Contains the filled Exchange orders.</description>
    <label>FilledExchangeOrder</label>
    <pluralLabel>FilledExchangeOrder</pluralLabel>
</CustomObject>

force-app/main/default/objects/FilledExchangeOrders__e/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>It represent a security on the exchange</description>
    <label>Security</label>
    <nameField>
        <label>Securies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ExchangeOrderHelper.cls
/**
 * ExchangeOrderHelper Description:
 * It process the exchange orders as per their order-side, order-type and other information.
 * creates the ExchangeOrderMatch records with sell-order and buy-order if match found and Fills the matched orders.
 * cancels the limit orders with Time-in-Force as "FoK (Fill or Kill)" if there is no match found.
 * @author developer
 */
public class ExchangeOrderHelper {

    public static void processExchangeOrder(List<Exchange_Order__c> newExchangeOrders){
        try{
            Set<Exchange_Order__c> existingOrders = new Set<Exchange_Order__c>();
            Map<Exchange_Order__c, Exchange_Order__c> matchedOrdersMap = new Map<Exchange_Order__c, Exchange_Order__c>();
            List<Exchange_Order_Match__c> exchangeOrderMatchesToCreate = new List<Exchange_Order_Match__c>();
            List<Exchange_Order__c> ordersToCancel = new List<Exchange_Order__c>();
            Boolean isSellOrder = false;
            existingOrders.addAll(getExistingOrders());
            for(Exchange_Order__c newExchangeOrder : newExchangeOrders){
                isSellOrder = (newExchangeOrder.Order_Side__c == Utility.SELLSIDE ? true : false);
                Exchange_Order__c matchedOrder = findOrderToMatch(newExchangeOrder, existingOrders);
                if(matchedOrder != null){
                    existingOrders.remove(matchedOrder);
                    matchedOrdersMap.put(newExchangeOrder, matchedOrder);
                    exchangeOrderMatchesToCreate.add(new Exchange_Order_Match__c(Price__c=newExchangeOrder.Price__c,Quantity__c=newExchangeOrder.Quantity__c,Sell_Order__c=(isSellOrder ? newExchangeOrder.Id : matchedOrder.Id),Buy_Order__c=(isSellOrder ? matchedOrder.Id : newExchangeOrder.Id)));
                }else if(newExchangeOrder.Order_Type__c == Utility.LIMITTYPE && newExchangeOrder.Time_in_Force__c == Utility.FOKLIMIT){
                    ordersToCancel.add(new Exchange_Order__c(id=newExchangeOrder.id, Status__c = Utility.CANCELSTATUS));
                }
            }
            if(!exchangeOrderMatchesToCreate.isEmpty()){
                Database.insert(exchangeOrderMatchesToCreate,false);
            }
            if(!ordersToCancel.isEmpty()){
                Database.update(ordersToCancel,false);
            }
        }catch(Exception ex){
            System.debug('There is some error while processing, please contact sys-admin: '+ex.getMessage());
        }
    }

    /**
     * findOrderToMatch Description
     *
     * @param newExchangeOrder (Exchange_Order__c): new order created
     * @param existingOrdersToVerify (Set<Exchange_Order__c>): existing exchange orders
     * @return Exchange_Order__c: matched exchange order, it returns null if no match found.
     */
    public static Exchange_Order__c findOrderToMatch(Exchange_Order__c newExchangeOrder, Set<Exchange_Order__c> existingOrdersToVerify){
        Exchange_Order__c matchedOrder = null;
        String orderSideToMatch = (newExchangeOrder.Order_Side__c == Utility.SELLSIDE ? Utility.BUYSIDE : Utility.SELLSIDE);
        for(Exchange_Order__c order : existingOrdersToVerify){
            if(order.Security__c == newExchangeOrder.Security__c &&
                order.Order_Side__c == orderSideToMatch && 
                order.Order_Type__c == newExchangeOrder.Order_Type__c && 
                order.Quantity__c == newExchangeOrder.Quantity__c &&
                order.Price__c == newExchangeOrder.Price__c){
                    matchedOrder = order;
                    break;
            }
        }
        return matchedOrder;
    }

    /**
     * getExistingOrders Description
     * queries the existing open exchange orders and returns.
     * @return List<Exchange_Order__c>: existing open exchange orders.
     * query: this has been placed in custom label and refered 
     * select id, Order_Side__c, Order_Total__c, Order_Type__c, Price__c,       Quantity__c, Security__c, 
        Status__c, Time_in_Force__c from Exchange_Order__c where Status__c = 'Open' ORDER BY CreatedDate
     */
    public static List<Exchange_Order__c> getExistingOrders(){
        List<Exchange_Order__c> existingOrders = new List<Exchange_Order__c>();
        existingOrders = Database.query(Label.SOQL_to_query_existing_orders);
        return existingOrders;
    }
    
    /**
     * fillMatchedOrders Description
     * fills the matched sell-order and buy-order
     * @param newExchangeOrderMatches (List<Exchange_Order_Match__c>): exchange orders to fill
     * @throws Class name here Write the class description
     */
    public static void fillMatchedOrders(List<Exchange_Order_Match__c> newExchangeOrderMatches){
        List<Exchange_Order__c> exchangeOrdersToFill = new List<Exchange_Order__c>();
        for(Exchange_Order_Match__c newExchangeOrderMatch : newExchangeOrderMatches){
            exchangeOrdersToFill.add(new Exchange_Order__c(id=newExchangeOrderMatch.Sell_Order__c, Status__c='Filled'));
            exchangeOrdersToFill.add(new Exchange_Order__c(id=newExchangeOrderMatch.Buy_Order__c, Status__c='Filled'));
        }
        if(!exchangeOrdersToFill.isEmpty()){
            Database.update(exchangeOrdersToFill,false);
            generateEmailEventForFilledOrders(exchangeOrdersToFill);
        }
    }
    
    /**
     * generateEmailEventForFilledOrders 
     * it creates events into Platform Event which in turn sends an email to owner on order fulfilment.
     * @param exchangeOrdersToFill (List<Exchange_Order__c>): order to push for event
     */
    public static void generateEmailEventForFilledOrders(List<Exchange_Order__c> exchangeOrdersToFill){
    List<FilledExchangeOrders__e> platformEventList = new List<FilledExchangeOrders__e>();
        for(Exchange_Order__c filledOrder : exchangeOrdersToFill){
            platformEventList.add(new FilledExchangeOrders__e(Email__c = filledOrder.Owner.Email, Order_Id__c = filledOrder.id));
        }
        if(!platformEventList.isEmpty()){
            EventBus.publish(platformEventList);
        }
    }
            
}