force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <description>Sell/Buy orders</description>
    <label>Exchange Order</label>
    <nameField>
        <displayFormat>ORDER-{00000}</displayFormat>
        <label>Exchange Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Side__c.field-meta.xml
<CustomField>
    <fullName>Order_Side__c</fullName>
    <description>Represents either a bid (buy) or an ask (sell) order</description>
    <inlineHelpText>Represents either a bid (buy) or an ask (sell) order</inlineHelpText>
    <label>Order Side</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Sell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Represents either a market or limit order</description>
    <inlineHelpText>Represents either a market or limit order</inlineHelpText>
    <label>Order Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Market</fullName>
            </value>
            <value>
                <fullName>Limit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Bid or ask price, only relevant for limit orders.</description>
    <inlineHelpText>Bid or ask price, only relevant for limit orders.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Represents the number of securities ordered (sell/buy)</description>
    <inlineHelpText>Represents the number of securities ordered (sell/buy)</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Security__c.field-meta.xml
<CustomField>
    <fullName>Security__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>holds ordered security</description>
    <inlineHelpText>holds ordered security</inlineHelpText>
    <label>Security</label>
    <referenceTo>Security__c</referenceTo>
    <relationshipLabel>Exchange Orders</relationshipLabel>
    <relationshipName>Exchange_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of the sell/buy order</description>
    <inlineHelpText>status of the sell/buy order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Time_in_Force__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Force__c</fullName>
    <description>Specifies the type and time till the limit order is valid.</description>
    <inlineHelpText>Specifies the type and time till the limit order is valid.</inlineHelpText>
    <label>Time in Force</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>GTC (Good Till Cancel)</fullName>
            </value>
            <value>
                <fullName>FoK (Fill or Kill)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/Exchange_Order_Match__c.object-meta.xml
<CustomObject>
    <description>representing the execution of a trade between sell and buy orders.</description>
    <label>Exchange Order Match</label>
    <nameField>
        <displayFormat>OrderMatch-{00000}</displayFormat>
        <label>Exchange Order Match Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Order Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Buy_Order__c.field-meta.xml
<CustomField>
    <fullName>Buy_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to exchange order(buy)</description>
    <inlineHelpText>lookup to exchange order(buy)</inlineHelpText>
    <label>Buy Order</label>
    <referenceTo>Exchange_Order__c</referenceTo>
    <relationshipLabel>Exchange Order Matches</relationshipLabel>
    <relationshipName>Exchange_Order_Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Price matched at.</description>
    <inlineHelpText>Price matched at.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Matched quantity</description>
    <inlineHelpText>Matched quantity</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exchange_Order_Match__c/fields/Sell_Order__c.field-meta.xml
<CustomField>
    <fullName>Sell_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup to exchange order(sell)</description>
    <inlineHelpText>lookup to exchange order(sell)</inlineHelpText>
    <label>Sell Order</label>
    <referenceTo>Exchange_Order__c</referenceTo>
    <relationshipLabel>Exchange Order Matches (Sell Order)</relationshipLabel>
    <relationshipName>Exchange_Order_Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Security__c/Security__c.object-meta.xml
<CustomObject>
    <description>It represent a security on the exchange</description>
    <label>Security</label>
    <nameField>
        <label>Securies Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Security__c/fields/Symbol__c.field-meta.xml
<CustomField>
    <fullName>Symbol__c</fullName>
    <label>Symbol</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUtility.cls
public class TestUtility{

    public static Security__c  createSecurity(String Name){
         Security__c security = new Security__c(Name = Name , Symbol__c = Name);
         insert security;
         return security;
    }
    public static Exchange_Order__c createOrder(String orderSide, String orderType, Integer price, Integer quantity, String TimeInForce){
         Exchange_Order__c order = new Exchange_Order__c(Order_Side__c =orderSide , Order_Type__c=orderType , Quantity__c=quantity, Price__c=price, Security__c = TestUtility.createSecurity('test').id, Time_in_Force__c = TimeInForce);
         insert order;
         return order;
    }
    
    public static Exchange_Order_Match__c createOrderMatch(String sellOrderId, String buyOrderId){
        Exchange_Order_Match__c orderMatch = new Exchange_Order_Match__c(Sell_Order__c=sellOrderId , Buy_Order__c=buyOrderId);
        insert orderMatch;
        return orderMatch;
    }
    
    public static Exchange_Order_Match__c getOrderMatch(String sellOrderId, String buyOrderId){
        return [select id,Sell_Order__c,Buy_Order__c from Exchange_Order_Match__c where Sell_Order__c=: sellOrderId and Buy_Order__c =: buyOrderId]; 
    }
    
    public static Exchange_Order__c getOrderById(String orderId){
        return [select id,Status__c from Exchange_Order__c where id =: orderId limit 1]; 
    }
}