force-app/main/default/objects/Exchange_Order__c/Exchange_Order__c.object-meta.xml
<CustomObject>
    <description>Sell/Buy orders</description>
    <label>Exchange Order</label>
    <nameField>
        <displayFormat>ORDER-{00000}</displayFormat>
        <label>Exchange Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exchange_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>status of the sell/buy order</description>
    <inlineHelpText>status of the sell/buy order</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exchange_Order__c/fields/Time_in_Force__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Force__c</fullName>
    <description>Specifies the type and time till the limit order is valid.</description>
    <inlineHelpText>Specifies the type and time till the limit order is valid.</inlineHelpText>
    <label>Time in Force</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day</fullName>
            </value>
            <value>
                <fullName>GTC (Good Till Cancel)</fullName>
            </value>
            <value>
                <fullName>FoK (Fill or Kill)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LimitOrderCleanerJob.cls
public class LimitOrderCleanerJob implements Database.Batchable<SObject>, Schedulable {

    //public List<Database.Error> erroredRecords = new List<Database.Error>();
    //public Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    public Database.Querylocator start(Database.BatchableContext bc){
        String query = 'Select id, Status__c from Exchange_Order__c where status__c = \'Open\' and Time_In_Force__c = \'Day\'';
        return Database.getQuerylocator(query);
    }

    public void execute (Database.BatchableContext bc,List<Exchange_Order__c> recordsBatch){
        List<Exchange_Order__c> ordersToCancel = new List<Exchange_Order__c>();
        for(Exchange_Order__c order : recordsBatch){
            order.status__c = Utility.CANCELSTATUS;
            ordersToCancel.add(order);
        }
        Database.SaveResult[] saveResultList = Database.update(ordersToCancel,false); //Results can be used for Success/failure processing.
        /*for(Database.SaveResult sr : saveResultList){
            if (sr.isSuccess()) {
                System.debug('Order Cancellation is successful for ID: ' + sr.getId());
            }
            else {              
                for(Database.Error err : sr.getErrors()) {
                    System.debug('An error occored with status code: '+err.getStatusCode()+' and with error: '+err.getMessage());                    
                    erroredRecords.add(err);
                }
            }
        }*/
    }

    public void finish(Database.BatchableContext bc){
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
        TotalJobItems, CreatedBy.Email
        FROM AsyncApexJob WHERE Id =
        :BC.getJobId()];
        //Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        /*String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('OrderCancellation job status ' + a.Status);
        mail.setPlainTextBody('\r\n'+'The batch Apex job processed ' + a.TotalJobItems +
        ' batches with '+ a.NumberOfErrors + ' failures. Following are the errors: '+erroredRecords);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});*/
    }
    
    public void execute (System.Schedulablecontext sc) {
        LimitOrderCleanerJob batchJob = new LimitOrderCleanerJob();
        Database.executeBatch(batchJob,200);
    }

}